language: java
jdk:
  - oraclejdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - codecov

deploy:
  provider: releases
  api_key: ${GIT_KEY}
  cleanup: false
  file_glob: true
  file: "build/distributions/logstash-intellij-plugin-*.zip"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^releasebuild_[0-9]+.*$"

after_deploy:
  - ./gradlew publishPlugin