language: java
jdk:
  - oraclejdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - echo 'Connect to CodeCov'
  - bash my_script.sh